# Generated by Django 5.2.1 on 2026-04-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0003_schoolclass_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolclass",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
