# Generated by Django 5.2.1 on 2026-04-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0006_alter_admission_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admission",
            old_name="alt_phone",
            new_name="parent_phone",
        ),
        migrations.RemoveField(
            model_name="admission",
            name="parent_gender",
        ),
        migrations.RemoveField(
            model_name="admission",
            name="relationship",
        ),
        migrations.AlterField(
            model_name="admission",
            name="admission_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="admission",
            name="application_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="admission",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="admission",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="admission",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="admission",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="admission",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="admission",
            name="parent_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="admission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
